version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #       - "8080:8080"
  #   environment:
  #       - NODE_ENV=production

  web:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./server/public/:/etc/nginx/html/
      - ./nginx-conf:/etc/nginx/conf.d

